name: Hello World

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  workflow_dispatch:
    jobs:
      hello_world:
        runs_on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
          - name: Hello 1
            run: echo "Hello world"
            shell: bash
